[package]
name = "human-readable-checksum"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
pbkdf2 = "0.12"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "checksum_bench"
harness = false